# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

#Announce both battery levels through BLE (central only)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
